<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Study 04 — A real reaction – xTB Metadynamics of Water</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-64a204ab8560d761af7679ceaba22944.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-8f53ae70cd472c10746adc2081c82a4c.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">xTB Metadynamics of Water</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="./index.html"> 
<span class="menu-text">Overview</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./01-sweep.html"> 
<span class="menu-text">Bias × size</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./02-pbc.html"> 
<span class="menu-text">PBC &amp; temperature</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./03-droplets.html"> 
<span class="menu-text">Droplets</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link active" href="./04-diels-alder.html" aria-current="page"> 
<span class="menu-text">Diels–Alder</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./05-mace.html"> 
<span class="menu-text">MACE-OFF23</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./06-kpush.html"> 
<span class="menu-text">kpush scaling</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./07-cv-design.html"> 
<span class="menu-text">CV design</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./08-corrections.html"> 
<span class="menu-text">Corrections</span></a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="https://github.com/tiangroup-uofa/xtb_metadynamics"> <i class="bi bi-github" role="img">
</i> 
<span class="menu-text">Repo</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
  <a href="" class="quarto-reader-toggle quarto-navigation-tool px-1" onclick="window.quartoToggleReader(); return false;" title="Toggle reader mode">
  <div class="quarto-reader-toggle-btn">
  <i class="bi"></i>
  </div>
</a>
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul class="collapse">
  <li><a href="#driving-and-properly-characterizing-a-dielsalder" id="toc-driving-and-properly-characterizing-a-dielsalder" class="nav-link active" data-scroll-target="#driving-and-properly-characterizing-a-dielsalder">Driving — and properly characterizing — a Diels–Alder</a></li>
  <li><a href="#can-mace-off23-reproduce-the-reaction-energetics-neb" id="toc-can-mace-off23-reproduce-the-reaction-energetics-neb" class="nav-link" data-scroll-target="#can-mace-off23-reproduce-the-reaction-energetics-neb">Can MACE-OFF23 reproduce the reaction energetics? (NEB)</a></li>
  <li><a href="#jul-31-follow-up-aug-7-is-the-barrier-gap-a-method-artifact" id="toc-jul-31-follow-up-aug-7-is-the-barrier-gap-a-method-artifact" class="nav-link" data-scroll-target="#jul-31-follow-up-aug-7-is-the-barrier-gap-a-method-artifact">Jul 31 follow-up (Aug 7) — is the barrier gap a method artifact?</a></li>
  <li><a href="#aug-7-follow-up-is-the-xtb-ts-also-a-mace-saddle" id="toc-aug-7-follow-up-is-the-xtb-ts-also-a-mace-saddle" class="nav-link" data-scroll-target="#aug-7-follow-up-is-the-xtb-ts-also-a-mace-saddle">Aug 7 follow-up — is the xTB TS also a MACE saddle?</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Study 04 — A real reaction</h1>
<p class="subtitle lead">Butadiene + ethylene → cyclohexene · GFN2</p>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="driving-and-properly-characterizing-a-dielsalder" class="level2">
<h2 class="anchored" data-anchor-id="driving-and-properly-characterizing-a-dielsalder">Driving — and properly characterizing — a Diels–Alder</h2>
<p>Using the same RMSD machinery pulled <em>toward</em> a product (<code>xtb --path</code>), the reaction runs: both new C–C σ-bonds form. But the path’s reported “barrier” (101 kcal/mol) is a <strong>biased-path artifact</strong> — the driver had to escalate the bias to connect. A relaxed concerted scan plus a Sella saddle optimization gives the real answer.</p>
<table class="table">
<thead>
<tr class="header">
<th>Quantity</th>
<th>Value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Forming C–C at TS</td>
<td>2.32 Å (symmetric)</td>
</tr>
<tr class="even">
<td>Imaginary frequency</td>
<td>−394 cm⁻¹ (exactly one)</td>
</tr>
<tr class="odd">
<td><strong>Concerted barrier</strong></td>
<td><strong>6.7 kcal/mol</strong> (scan and Sella agree)</td>
</tr>
<tr class="even">
<td>Reaction energy</td>
<td>−57.6 kcal/mol</td>
</tr>
<tr class="odd">
<td><del><code>--path</code> “barrier”</del></td>
<td><del>101 kcal/mol</del> — not physical</td>
</tr>
</tbody>
</table>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="assets/reaction_profile.png" class="img-fluid figure-img" width="560"></p>
<figcaption>Concerted reaction profile: barrier 6.7 kcal/mol at forming-bond distance 2.32 Å, then downhill to the product.</figcaption>
</figure>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Ties back to the metadynamics theme
</div>
</div>
<div class="callout-body-container callout-body">
<p>Enhanced sampling <em>finds</em> that a transition is reachable, but a quantitative barrier needs a proper TS treatment — the RMSD bias alone is chemically blind. (Also: xtb has no TS optimizer — <code>--optts</code> is not a flag; use Sella. And read the <code>vibspectrum</code> file for frequencies, not the <code>--hess</code> stdout.)</p>
</div>
</div>
<p><a href="https://github.com/tiangroup-uofa/xtb_metadynamics/blob/main/sweep/diels_alder/FINDINGS_diels_alder.md">Full findings — FINDINGS_diels_alder.md →</a></p>
</section>
<section id="can-mace-off23-reproduce-the-reaction-energetics-neb" class="level2">
<h2 class="anchored" data-anchor-id="can-mace-off23-reproduce-the-reaction-energetics-neb">Can MACE-OFF23 reproduce the reaction energetics? (NEB)</h2>
<p>Next question: does the MACE-OFF23 surrogate get reaction <em>energetics</em> right with <strong>no fine-tuning</strong>? xTB has a built-in path search; MACE doesn’t, so we build the profile with a climbing-image <strong>NEB</strong> (ASE) and compare.</p>
<table class="table">
<thead>
<tr class="header">
<th>quantity</th>
<th style="text-align: center;">GFN2-xTB (built-in path)</th>
<th style="text-align: center;">MACE-OFF23 (NEB)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>activation barrier</td>
<td style="text-align: center;">6.7 kcal/mol</td>
<td style="text-align: center;"><strong>36.2 kcal/mol</strong></td>
</tr>
<tr class="even">
<td>reaction energy</td>
<td style="text-align: center;">−57.6 kcal/mol</td>
<td style="text-align: center;"><strong>−36.1 kcal/mol</strong></td>
</tr>
<tr class="odd">
<td>TS forming C–C</td>
<td style="text-align: center;">2.32 Å</td>
<td style="text-align: center;">2.03 / 1.98 Å (slightly asynchronous)</td>
</tr>
</tbody>
</table>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="assets/neb_da_mace_vs_xtb.png" class="img-fluid figure-img" width="760"></p>
<figcaption>Minimum energy path and energetics: MACE-OFF23 (CI-NEB) vs GFN2-xTB (built-in path).</figcaption>
</figure>
</div>
<p><strong>Outcome (2): same TS location (~2.0–2.3 Å), very different energetics.</strong> And it’s the <em>physical</em> difference — experiment/DFT give a barrier ≈ 22–27 kcal/mol and ΔH ≈ −40. GFN2-xTB badly underestimates the barrier (6.7) and overbinds the product (−57.6); MACE-OFF23 (DFT-trained) is much closer on both, off the shelf. The refined MACE TS is a genuine first-order saddle (one imaginary mode, −740 cm⁻¹) and slightly <strong>asynchronous</strong> — MACE makes the perfectly synchronous geometry a second-order saddle.</p>
<section id="where-do-the-two-potentials-actually-differ" class="level3">
<h3 class="anchored" data-anchor-id="where-do-the-two-potentials-actually-differ">Where do the two potentials actually differ?</h3>
<p>Digging into the benchmark: the disagreement is a <strong>reactive-region</strong> effect. The energy difference ΔE = E_MACE − E_xTB is ~0 for the separated reactants, grows as the bonds form, peaks in the TS region, and leaves a persistent ~+23 kcal/mol product offset — <strong>not a constant shift.</strong></p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="assets/neb_energy_diff.png" class="img-fluid figure-img" width="680"></p>
<figcaption>Energy-difference profile (both potentials relaxed at each point along the reaction coordinate).</figcaption>
</figure>
</div>
<p>And the forces: on rattled reaction-path geometries the MACE and xTB force vectors are <strong>directionally almost identical (cosine 0.98)</strong>, but the <strong>magnitude gap (RMSE) spikes in the TS region</strong> — exactly where the energy difference peaks.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="assets/neb_force_agreement.png" class="img-fluid figure-img" width="680"></p>
<figcaption>Force RMSE and cosine similarity along the path — agreement is near-perfect in the reactant/product basins and degrades only in the TS region.</figcaption>
</figure>
</div>
<p>Both potentials agree the reaction is a <strong>concerted, synchronous</strong> cycloaddition — the two forming bonds contract together (b1 ≈ b2 along the whole path), with only MACE’s TS marginally asynchronous (2.03 / 1.98 Å). They differ in energetics, not mechanism.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="assets/neb_bond_evolution.png" class="img-fluid figure-img" width="680"></p>
<figcaption>Forming-bond evolution: b1 and b2 contract synchronously for both methods; MACE’s TS carries a small 0.05 Å asynchrony.</figcaption>
</figure>
</div>
<p>The MACE barrier is <strong>numerically converged — 35.9 ± 1.0 kcal/mol for ≥11 NEB images</strong> (9 images is too few to resolve the TS: the barrier collapses to ~18 and the TS drifts to 2.5 Å), and it is cross-validated by the independent relaxed scan (36.0) and the Sella-refined saddle (36.2).</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="assets/neb_barrier_convergence.png" class="img-fluid figure-img" width="560"></p>
<figcaption>Activation barrier vs NEB image count: converged for ≥11 images; 9 is under-resolved.</figcaption>
</figure>
</div>
<p><strong>Literature context:</strong> experiment gives a barrier ≈ 27.5 and ΔH ≈ −40 kcal/mol. xTB (6.7 / −57.6) is qualitatively wrong on both; MACE-OFF23 (36 / −36…−41) nails the reaction energy and is in the right kinetic regime, though it overestimates the barrier by ~9 kcal/mol.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>What this tells the correction framework
</div>
</div>
<div class="callout-body-container callout-body">
<p>MACE and xTB agree on geometry, mechanism, and force <em>direction</em> (cosine 0.98) and disagree on energy/force <em>magnitude</em>, <strong>localized in the bond-forming region.</strong> So a global energy shift is ruled out (ΔE is zero at the reactant); the direction-agrees / magnitude-differs signature points to a <strong>force-scaling</strong> correction, and the localization points to an <strong>environment/coordination-dependent</strong> (or delta) form. The NEB pipeline already wraps every potential in a <code>CorrectedCalculator</code> with these plug-in models — fitting one is the immediate next step.</p>
</div>
</div>
<p><a href="https://github.com/tiangroup-uofa/xtb_metadynamics/blob/main/sweep/diels_alder/FINDINGS_neb.md">NEB findings — FINDINGS_neb.md →</a></p>
</section>
</section>
<section id="jul-31-follow-up-aug-7-is-the-barrier-gap-a-method-artifact" class="level2">
<h2 class="anchored" data-anchor-id="jul-31-follow-up-aug-7-is-the-barrier-gap-a-method-artifact">Jul 31 follow-up (Aug 7) — is the barrier gap a method artifact?</h2>
<p>The obvious objection to the ~30 kcal/mol MACE–xTB barrier gap: MACE used NEB, xTB used its built-in path search. Maybe the gap is just a <strong>path-method mismatch</strong>. To rule that out we ran <em>both</em> potentials through the <strong>identical</strong> standardized NEB (13 images, k=0.5, FIRE / <code>NEBOptimizer</code>, fmax 0.05, climbing image, same concerted-scan seed).</p>
<ul>
<li><strong><code>xtb-python</code> stability gate passed</strong> — single-points, forces, and geometry optimization are reproducible (repeat-evaluation energy std ≈ 5e-14 eV), so the backend is trustworthy for the full band.</li>
<li><strong>MACE’s barrier is method-invariant: ~36 kcal/mol across the relaxed scan (36.0), the Sella saddle (36.2), and the standardized NEB (36–37).</strong> It is also numerically converged (35.9 ± 1.0 for ≥11 images).</li>
<li><strong>xTB ASE-NEB fails <em>physically</em> under the same settings</strong> — the band does not form a sensible path; atoms in the “TS” images fly apart (reported forming C–C of ~7–18 Å) and the apparent barrier balloons to 240–250 kcal/mol under both optimizers.</li>
</ul>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Important</span>This is a PES/algorithm compatibility issue, not a backend failure
</div>
</div>
<div class="callout-body-container callout-body">
<p>The same <code>xtb-python</code> that passed the stability gate produces a clean single-point everywhere; only the <em>band optimization</em> on xTB’s flatter, low-barrier surface diverges under these settings (a file-based binary xTB would hit the identical problem). So the valid xTB reference stays the constrained relaxed scan + verified TS (6.7 kcal/mol). <strong>Because MACE’s barrier is the same ~36 kcal/mol no matter how it is computed, the ~30 kcal/mol MACE–xTB gap is a genuine difference between the two potential-energy surfaces — it is not explained by the original path-method mismatch.</strong></p>
</div>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="assets/a2_standardized_neb.png" class="img-fluid figure-img" width="720"></p>
<figcaption>Standardized NEB: MACE gives a consistent ~36 kcal/mol barrier; the xTB band does not converge to a physical path under the identical settings (shown as its valid relaxed-scan reference instead).</figcaption>
</figure>
</div>
<section id="barrier-region-error-analysis" class="level3">
<h3 class="anchored" data-anchor-id="barrier-region-error-analysis">Barrier-region error analysis</h3>
<p>Where along the reaction coordinate does the MACE↔︎xTB disagreement live? We partitioned 152 rattled path geometries into five regions by forming C–C distance and measured raw MACE-vs-xTB force RMSE, cosine, and energy discrepancy per region.</p>
<table class="table">
<colgroup>
<col style="width: 16%">
<col style="width: 27%">
<col style="width: 27%">
<col style="width: 27%">
</colgroup>
<thead>
<tr class="header">
<th>region (forming C–C)</th>
<th style="text-align: center;">force RMSE (eV/Å)</th>
<th style="text-align: center;">cosine</th>
<th style="text-align: center;">ΔE vs reactant (kcal/mol)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>reactant basin (&gt;2.9 Å)</td>
<td style="text-align: center;">0.39</td>
<td style="text-align: center;">0.996</td>
<td style="text-align: center;">0 (ref)</td>
</tr>
<tr class="even">
<td>pre-TS rising (2.4–2.9)</td>
<td style="text-align: center;">0.43</td>
<td style="text-align: center;">0.991</td>
<td style="text-align: center;">8.7</td>
</tr>
<tr class="odd">
<td><strong>TS region (1.96–2.4)</strong></td>
<td style="text-align: center;"><strong>0.83</strong></td>
<td style="text-align: center;"><strong>0.950</strong></td>
<td style="text-align: center;"><strong>36.5</strong></td>
</tr>
<tr class="even">
<td><strong>post-TS (1.7–1.96)</strong></td>
<td style="text-align: center;"><strong>0.96</strong></td>
<td style="text-align: center;">0.964</td>
<td style="text-align: center;">31.3</td>
</tr>
<tr class="odd">
<td>product basin (&lt;1.7 Å)</td>
<td style="text-align: center;">0.33</td>
<td style="text-align: center;">0.997</td>
<td style="text-align: center;">23.1</td>
</tr>
</tbody>
</table>
<ul>
<li>In the <strong>reactant/product basins</strong> agreement is excellent — cosine ≈ 0.996–0.997 and low RMSE.</li>
<li>In the <strong>TS/post-TS region the force RMSE rises ~2.5–2.9×</strong> (to 0.83–0.96 eV/Å), the <strong>TS cosine drops to ~0.950</strong>, and the <strong>energy discrepancy peaks in the same reactive window</strong> — the disagreement is concentrated exactly where the forming bonds are half-made and the geometry is most distorted.</li>
</ul>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="assets/neb_regionwise_error.png" class="img-fluid figure-img" width="680"></p>
<figcaption>Region-wise MACE↔︎xTB force RMSE and cosine: near-perfect in the basins, degrading sharply through the TS / post-TS region.</figcaption>
</figure>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Careful with the “why”
</div>
</div>
<div class="callout-body-container callout-body">
<p>That the errors <em>concentrate</em> in the distorted barrier region is directly measured here. The natural explanation — that such highly distorted geometries are under-represented in the foundation model’s training distribution — is a <strong>supported hypothesis, not a demonstrated fact</strong>; this dataset shows <em>where</em> the error is, not <em>why</em>. It motivates, but does not prove, targeted data enrichment.</p>
</div>
</div>
<p><a href="https://github.com/tiangroup-uofa/xtb_metadynamics/blob/main/sweep/diels_alder/FINDINGS_jul31.md">Jul 31 follow-up findings — FINDINGS_jul31.md →</a></p>
</section>
</section>
<section id="aug-7-follow-up-is-the-xtb-ts-also-a-mace-saddle" class="level2">
<h2 class="anchored" data-anchor-id="aug-7-follow-up-is-the-xtb-ts-also-a-mace-saddle">Aug 7 follow-up — is the xTB TS also a MACE saddle?</h2>
<p>The ~30 kcal/mol barrier gap was confirmed as real on identical geometries (Phase Jul 31). But a natural follow-up: does the native xTB transition state (2.32 Å forming C–C) also serve as the MACE transition state? Or does MACE have its own distinct saddle nearby?</p>
<p>We used the verified xTB TS as a starting point for a <strong>MACE saddle search via Sella</strong>, then tested whether the result is robust to small perturbations.</p>
<section id="identical-geometry-cross-check" class="level3">
<h3 class="anchored" data-anchor-id="identical-geometry-cross-check">Identical-geometry cross-check</h3>
<p>First, frozen-geometry evaluation confirmed the gap is intrinsic:</p>
<table class="table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>Calculation</th>
<th>xTB</th>
<th>MACE @ xTB geoms</th>
<th>Difference</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Barrier at frozen xTB TS</strong></td>
<td><strong>6.7 kcal/mol</strong></td>
<td><strong>27.9 kcal/mol</strong></td>
<td><strong>−21.2</strong></td>
</tr>
<tr class="even">
<td>Force residual at xTB TS</td>
<td>0.00093 eV/Å</td>
<td><strong>1.84 eV/Å</strong></td>
<td>—</td>
</tr>
</tbody>
</table>
<p>The xTB TS is a true saddle on xTB’s PES (tiny residual force). On MACE’s PES, the same geometry carries <strong>large residual forces (1.84 eV/Å)</strong> — it is NOT a saddle point on MACE.</p>
</section>
<section id="mace-saddle-search-from-xtb-ts" class="level3">
<h3 class="anchored" data-anchor-id="mace-saddle-search-from-xtb-ts">MACE saddle search from xTB TS</h3>
<p>Started Sella at the xTB TS geometry. Result:</p>
<table class="table">
<thead>
<tr class="header">
<th>Metric</th>
<th>Value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Converged</strong></td>
<td>YES (66 iterations)</td>
</tr>
<tr class="even">
<td><strong>MACE TS forming C–C</strong></td>
<td><strong>2.004 Å</strong></td>
</tr>
<tr class="odd">
<td><strong>xTB TS forming C–C</strong></td>
<td>2.315 Å</td>
</tr>
<tr class="even">
<td><strong>Geometric shift</strong></td>
<td><strong>0.311 Å</strong></td>
</tr>
<tr class="odd">
<td><strong>MACE barrier at converged TS</strong></td>
<td><strong>35.8 kcal/mol</strong></td>
</tr>
<tr class="even">
<td><strong>Independent NEB barrier (reference)</strong></td>
<td>36.0 kcal/mol</td>
</tr>
<tr class="odd">
<td><strong>First-order saddle?</strong></td>
<td>YES — one imaginary mode ✓</td>
</tr>
</tbody>
</table>
<p>The converged MACE TS is <strong>distinct from the xTB TS</strong> in both location and energy, yet it <strong>matches the independently obtained NEB barrier</strong> (35.8 vs 36.0 kcal/mol, RMSD &lt; 0.001 Å). This agreement across two separate methods is strong evidence for a well-defined MACE saddle.</p>
</section>
<section id="robustness-small-perturbations-along-the-reaction-mode" class="level3">
<h3 class="anchored" data-anchor-id="robustness-small-perturbations-along-the-reaction-mode">Robustness: small perturbations along the reaction mode</h3>
<p>To verify the MACE saddle is not an artifact, we created four small perturbations (±0.02 Å, ±0.05 Å) along the Hessian’s imaginary eigenvector and ran Sella from each.</p>
<p><strong>Result: perfect recovery to the same saddle.</strong></p>
<table class="table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>Perturbation</th>
<th>Iterations to converge</th>
<th>Barrier (kcal/mol)</th>
<th>RMSD to reference (Å)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>−0.05 Å</td>
<td>38</td>
<td>35.806</td>
<td>5.0e−6</td>
</tr>
<tr class="even">
<td>−0.02 Å</td>
<td>30</td>
<td>35.806</td>
<td>1.6e−6</td>
</tr>
<tr class="odd">
<td>+0.02 Å</td>
<td>37</td>
<td>35.806</td>
<td>1.6e−6</td>
</tr>
<tr class="even">
<td>+0.05 Å</td>
<td>61</td>
<td>35.806</td>
<td>1.6e−6</td>
</tr>
<tr class="odd">
<td><strong>Spread</strong></td>
<td>—</td>
<td><strong>0.000 kcal/mol</strong></td>
<td><strong>&lt; 1e−5 Å</strong></td>
</tr>
</tbody>
</table>
<p>All four perturbations converge back to <strong>the exact same MACE saddle</strong> (barrier 35.806 ± 0.000 kcal/mol, zero geometry spread). This is characteristic of a well-isolated, robust first-order saddle point — not a numerical artifact or an optimizer quirk.</p>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Important</span>The barrier disagreement is a genuine PES difference
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>The xTB and MACE potential-energy surfaces describe fundamentally different reaction barriers in the same geometric region.</strong></p>
<p>The 29 kcal/mol gap is not explained by: - Path-search methodology (identical frozen geometries still show 21 kcal/mol difference) - Lack of MACE TS convergence (independent methods consistently recover ~36 kcal/mol) - Optimizer artifacts (robustness test shows zero variability under perturbations)</p>
<p>The two models agree on mechanism (concerted, synchronous bond-forming, ~2.0–2.3 Å TS region) but assign very different barrier heights.</p>
</div>
</div>
<p><a href="https://github.com/tiangroup-uofa/xtb_metadynamics/blob/main/sweep/diels_alder/PHASE1_COMPLETE_FINDINGS.md">Phase 1 complete findings — PHASE1_COMPLETE_FINDINGS.md →</a></p>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
      &nbsp;
    </div>   
    <div class="nav-footer-center">
<p>xTB metadynamics of water · Tian group · <a href="https://github.com/tiangroup-uofa/xtb_metadynamics">github</a></p>
</div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>




</body></html>